swagger: "2.0"
info:
  title: API for Fabric8 Analytics Core Jobs
  version: "0.1"
basePath: "/api/v1/"
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  auth_token:
    type: "apiKey"
    name: "auth-token"
    in: "header"

paths:
  /generate-token:
    get:
      tags: [Authentication]
      operationId: f8a_jobs.api_v1.generate_token
      summary: Get authentization token for communicating with this service
      responses:
        200:
          description: Authentization token
        401:
          description: No suitable permissions
  /logout:
    put:
      tags: [Authentication]
      operationId: f8a_jobs.api_v1.logout
      summary: Clean session
      responses:
        201:
          description: Successfully logged out
        401:
          description: No user logged in
  /authorized:
    get:
      tags: [Authentication]
      operationId: f8a_jobs.api_v1.authorized
      summary: Authentication redirection
      responses:
        200:
          description: Successfully authorized
  /liveness:
    get:
      tags: [Service settings]
      operationId: f8a_jobs.api_v1.get_liveness
      summary: Get job service liveness
      responses:
        200:
          description: Service is alive
  /readiness:
    get:
      tags: [Service settings]
      operationId: f8a_jobs.api_v1.get_readiness
      summary: Get job service readiness
      responses:
        200:
          description: Service is ready
  /service/state:
    get:
      tags: [Service settings]
      operationId: f8a_jobs.api_v1.get_service_state
      summary: Get job service state
      security:
        - auth_token: []
      responses:
        200:
          description: State of the job service
        401:
          description: No suitable permissions
    put:
      tags: [Service settings]
      operationId: f8a_jobs.api_v1.put_service_state
      summary: Pause or resume job execution
      parameters:
        - $ref: "#/parameters/state"
      security:
        - auth_token: []
      responses:
        200:
          description: Information about job execution
        401:
          description: No suitable permissions
  /jobs:
    get:
      tags: [Jobs options]
      operationId: f8a_jobs.api_v1.get_jobs
      summary: Get all pending jobs
      parameters:
        - $ref: "#/parameters/job_type"
      security:
        - auth_token: []
      responses:
        200:
          description: All active jobs
        401:
          description: No suitable permissions
  '/jobs/{job_id}':
    delete:
       tags: [Jobs options]
       operationId: f8a_jobs.api_v1.delete_jobs
       summary: Delete a job
       parameters:
        - $ref: "#/parameters/job_id_path"
       security:
        - auth_token: []
       responses:
         200:
           description: Job with the given id was removed
         401:
           description: No suitable permissions
    put:
      tags: [Jobs options]
      operationId: f8a_jobs.api_v1.put_jobs
      summary: Jobs state manipulation
      parameters:
        - $ref: "#/parameters/job_id_path"
        - $ref: "#/parameters/state"
      security:
        - auth_token: []
      responses:
        200:
          description: New analyses job scheduled
        401:
          description: No suitable permissions
  '/jobs/clean-failed':
    delete:
       tags: [Jobs options]
       operationId: f8a_jobs.api_v1.delete_clean_failed
       summary: Delete all failed jobs
       security:
         - auth_token: []
       responses:
         200:
           description: All failed jobs were deleted
         400:
           description: Error describing issue in your SQL query or error on querying
         401:
           description: No suitable permissions
  '/debug/show-select-query':
    post:
       tags: [Debug]
       operationId: f8a_jobs.api_v1.post_show_select_query
       summary: Show SQL query that will be used in case of filter parametrized jobs
       parameters:
        - name: filter_definition
          in: body
          required: true
          description: JSON describing SQL query
          schema:
            $ref: "#/definitions/Filter"
       security:
        - auth_token: []
       responses:
         200:
           description: Constructed SQL query for the given filter definition
         400:
           description: Error describing issue in your SQL query
         401:
           description: No suitable permissions
  '/debug/expand-filter-query':
    post:
       tags: [Debug]
       operationId: f8a_jobs.api_v1.post_expand_filter_query
       summary: Use filter to query database and show results that matched given filter
       parameters:
        - name: filter_definition
          in: body
          required: true
          description: JSON describing SQL query
          schema:
            $ref: "#/definitions/Filter"
       security:
        - auth_token: []
       responses:
         200:
           description: Matched records in database for the given filter definition
         401:
           description: No suitable permissions
  '/debug/analyses-report':
    get:
       tags: [Debug]
       operationId: f8a_jobs.api_v1.get_analyses_report
       summary: View brief report of the current system analyses status
       parameters:
        - $ref: "#/parameters/ecosystem"
        - $ref: "#/parameters/from_date"
        - $ref: "#/parameters/to_date"
       security:
        - auth_token: []
       responses:
         200:
           description: A brief report of the analyses running
         401:
           description: No suitable permissions
  '/debug/queue-attributes':
    get:
       tags: [Debug]
       operationId: f8a_jobs.api_v1.get_queue_attributes
       summary: View attributes of queues available
       security:
        - auth_token: []
       responses:
         200:
           description: A report containing queue attributes info
         401:
           description: No suitable permissions
  '/debug/queue-purge':
    post:
      tags: [Debug]
      operationId: f8a_jobs.api_v1.post_queue_purge
      summary: Purge given SQS queues
      parameters:
        - $ref: "#/parameters/queues"
      security:
        - auth_token: []
      responses:
        200:
          description: Queues purged
        401:
          description: No suitable permissions
  '/debug/github-tokens':
    get:
       tags: [Debug]
       operationId: f8a_jobs.api_v1.get_gh_tokens_rate_limits
       summary: Show current API rate limits on GitHub tokens
       security:
        - auth_token: []
       responses:
         200:
           description: API rate limits on GitHub tokens
         401:
           description: No suitable permissions
  '/jobs/flow-scheduling':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.post_flow_scheduling
      summary: Schedule a new job for analyses
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - name: kwargs
          in: body
          required: false
          description: Job keyword arguments for analyses scheduling
          schema:
            $ref: "#/definitions/FlowKwargs"
      security:
        - auth_token: []
      responses:
        201:
          description: New analyses job scheduled
        401:
          description: No suitable permissions
  '/jobs/github-manifests':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.github_manifests
      summary: Collect and process manifest files from given GitHub repositories
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - $ref: "#/parameters/skip_if_exists"
        - name: kwargs
          in: body
          required: true
          description: Keyword arguments for GitHub manifests job
          schema:
            $ref: "#/definitions/GitHubManifestsKwargs"
      security:
        - auth_token: []
      responses:
        201:
          description: New job successfully scheduled
        401:
          description: No suitable permissions
  '/jobs/aggregate-github-manifest-pkgs':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.aggregate_github_manifest_pkgs
      summary: Aggregate package names from GitHub manifests
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - $ref: "#/parameters/bucket_name"
        - $ref: "#/parameters/object_key"
        - $ref: "#/parameters/ecosystem"
        - name: kwargs
          in: body
          required: true
          description: Keyword arguments for GitHub manifests job
          schema:
            $ref: "#/definitions/GitHubAggregateManifestPkgsKwargs"
      security:
        - auth_token: []
      responses:
        201:
          description: New job successfully scheduled
        401:
          description: No suitable permissions
  '/jobs/aggregate-crowd-source-tags':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.aggregate_crowd_source_tags
      summary: Aggregate crowd-sourced tags
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - $ref: "#/parameters/ecosystem"
      security:
        - auth_token: []
      responses:
        201:
          description: Read, verify, aggregate verify tags store them on S3
        401:
          description: No suitable permissions
  '/jobs/selective-flow-scheduling':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.post_selective_flow_scheduling
      summary: Schedule a new job for analyses only with selected tasks marked for execution
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - name: kwargs
          in: body
          required: false
          description: Job keyword arguments for selective analyses scheduling
          schema:
            $ref: "#/definitions/SelectiveKwargs"
      security:
        - auth_token: []
      responses:
        201:
          description: New analyses job scheduled
        401:
          description: No suitable permissions
  '/jobs/analyses':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.post_analyses
      summary: Analyse packages from index
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - $ref: "#/parameters/popular"
        - $ref: "#/parameters/ecosystem"
        - $ref: "#/parameters/count"
        - $ref: "#/parameters/nversions"
        - $ref: "#/parameters/force"
        - $ref: "#/parameters/recursive_limit"
        - $ref: "#/parameters/force_graph_sync"
      security:
        - auth_token: []
      responses:
        201:
          description: New analyses job scheduled
        401:
          description: No suitable permissions
  '/jobs/maven-releases':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.post_maven_releases
      summary: Add job for scheduling new maven releases
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
      security:
        - auth_token: []
      responses:
        201:
          description: New maven releases job scheduled
        401:
          description: No suitable permissions
    get:
      tags: [Jobs options]
      operationId: f8a_jobs.api_v1.get_maven_releases
      summary: Get last used offset to maven indexer
      security:
        - auth_token: []
      responses:
        200:
          description: Offset to maven indexer
        401:
          description: No suitable permissions
    put:
      tags: [Jobs options]
      operationId: f8a_jobs.api_v1.put_maven_releases
      summary: Adjust offset to maven indexer that should be used
      parameters:
        - $ref: "#/parameters/offset"
      security:
        - auth_token: []
      responses:
        201:
          description: Offset adjusted
        401:
          description: No suitable permissions
  '/jobs/aggregate-topics':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.post_aggregate_topics
      summary: Aggregate all topics collected from GitHub and store them on S3
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - $ref: "#/parameters/ecosystem"
        - $ref: "#/parameters/from_date"
        - $ref: "#/parameters/to_date"
        - $ref: "#/parameters/bucket_name"
        - $ref: "#/parameters/object_key"
      security:
        - auth_token: []
      responses:
        201:
          description: Aggregate gathered topics and store them on S3
        401:
          description: No suitable permissions
  '/jobs/kronos-data-update':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.post_kronos_data_update
      summary: All 
      parameters:
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"  
        - $ref: "#/parameters/ecosystem"
        - $ref: "#/parameters/past_days"
        - $ref: "#/parameters/kronos_bucket"
        - $ref: "#/parameters/user_persona"
      security:
        - auth_token: []
      responses:
        201:
          description: Read User input from RDS and update Kronos S3
        401:
          description: No suitable permissions        
  '/jobs/github-most-starred':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.github_most_starred
      summary: GH most starred
      parameters:
        - $ref: "#/parameters/ecosystem"
        - $ref: "#/parameters/count"
        - $ref: "#/parameters/min_stars"
        - $ref: "#/parameters/max_stars"
        - $ref: "#/parameters/skip_if_exists"
        - $ref: "#/parameters/start_from"
        - $ref: "#/parameters/recursive_limit"
        - $ref: "#/parameters/force"
      security:
        - auth_token: []
      responses:
        201:
          description: New analyses job scheduled
        401:
          description: No suitable permissions
  '/jobs/clean-postgres':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.post_clean_postgres
      summary: Clean PostgreSQL results
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - $ref: "#/parameters/from_date"
        - $ref: "#/parameters/to_date"
        - $ref: "#/parameters/clean_unfinished"
      security:
        - auth_token: []
      responses:
        201:
          description: New analyses job scheduled
        401:
          description: No suitable permissions
  '/jobs/sync-to-graph':
    post:
      tags: [Add new jobs]
      operationId: f8a_jobs.api_v1.post_sync_to_graph
      summary: Sync all finished analyses to graph
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - $ref: "#/parameters/start"
        - $ref: "#/parameters/end"
      security:
        - auth_token: []
      responses:
        201:
          description: Sync to graph scheduled
        401:
          description: No suitable permissions
  '/bookkeeping':
    get:
       tags: [BookKeeping]
       operationId: f8a_jobs.api_v1.bookkeeping_all
       summary: Retrieve BookKeeping data
       security:
        - auth_token: []
       responses:
         200:
           description: Summary of bookkeeping data
  '/bookkeeping/{ecosystem}':
    get:
       tags: [BookKeeping]
       operationId: f8a_jobs.api_v1.bookkeeping_ecosystem
       summary: Retrieve BookKeeping data for given ecosystem
       parameters:
        - $ref: "#/parameters/ecosystem_path"
       security:
        - auth_token: []
       responses:
         200:
           description: Summary of bookkeeping data for given ecosystem
  '/bookkeeping/{ecosystem}/{package}':
    get:
       tags: [BookKeeping]
       operationId: f8a_jobs.api_v1.bookkeeping_ecosystem_package
       summary: Retrieve BookKeeping data for given ecosystem and package
       parameters:
        - $ref: "#/parameters/ecosystem_path"
        - $ref: "#/parameters/package_name"
       security:
        - auth_token: []
       responses:
         200:
           description: Summary of bookkeeping data for given ecosystem and package
  '/bookkeeping/{ecosystem}/{package}/{version}':
    get:
       tags: [BookKeeping]
       operationId: f8a_jobs.api_v1.bookkeeping_epv
       summary: Retrieve BookKeeping data for given ecosystem, package and version
       parameters:
        - $ref: "#/parameters/ecosystem_path"
        - $ref: "#/parameters/package_name"
        - $ref: "#/parameters/version_full"
       security:
        - auth_token: []
       responses:
         200:
           description: Summary of bookkeeping data for given ecosystem, package and version
  '/bookkeeping/upstreams':
    get:
       tags: [BookKeeping]
       operationId: f8a_jobs.api_v1.bookkeeping_upstreams_all
       summary: Retrieve BookKeeping data for monitored upstreams
       parameters:
        - $ref: "#/parameters/active_only"
        - $ref: "#/parameters/count"
       security:
        - auth_token: []
       responses:
         200:
           description: List of monitored upstreams
  '/bookkeeping/upstreams/{ecosystem}':
    get:
       tags: [BookKeeping]
       operationId: f8a_jobs.api_v1.bookkeeping_upstreams_ecosystem
       summary: Retrieve BookKeeping data for monitored upstreams for given ecosystem
       parameters:
        - $ref: "#/parameters/active_only"
        - $ref: "#/parameters/count"
        - $ref: "#/parameters/ecosystem_path"
       security:
        - auth_token: []
       responses:
         200:
           description: List of monitored upstreams for given ecosystem
  '/bookkeeping/upstreams/{ecosystem}/{package}':
    get:
       tags: [BookKeeping]
       operationId: f8a_jobs.api_v1.bookkeeping_upstreams_ecosystem_package
       summary: Retrieve BookKeeping data for monitored upstreams for given ecosystem and package
       parameters:
        - $ref: "#/parameters/active_only"
        - $ref: "#/parameters/count"
        - $ref: "#/parameters/ecosystem_path"
        - $ref: "#/parameters/package_name"
       security:
        - auth_token: []
       responses:
         200:
           description: List of monitored upstreams for given ecosystem and package


  '/graphsync/pending':
    get:
       tags: [GraphSync]
       operationId: f8a_jobs.api_v1.retrieve_graphsync_all
       summary: Retrieve Pending Graphsync data for all ecosystems
       parameters:
        - $ref: "#/parameters/count"
       security:
        - auth_token: []
       responses:
         200:
           description: Summary of Pending Graphsync data for all ecosystems
  '/graphsync/pending/{ecosystem}':
    get:
       tags: [GraphSync]
       operationId: f8a_jobs.api_v1.retrieve_graphsync_ecosystem
       summary: Retrieve Pending Graphsync data for given ecosystem
       parameters:
        - $ref: "#/parameters/ecosystem_path"
        - $ref: "#/parameters/count"
       security:
        - auth_token: []
       responses:
         200:
           description: Summary of pending graphsync data for given ecosystem
  '/graphsync/pending/{ecosystem}/{package}':
    get:
       tags: [GraphSync]
       operationId: f8a_jobs.api_v1.retrieve_graphsync_ecosystem_package
       summary: Retrieve Pending Graphsync data for given ecosystem and package
       parameters:
        - $ref: "#/parameters/ecosystem_path"
        - $ref: "#/parameters/package_name"
        - $ref: "#/parameters/count"
       security:
        - auth_token: []
       responses:
         200:
           description: Summary of pending graphsync data for given ecosystem and package
  '/graphsync/pending/{ecosystem}/{package}/{version}':
    get:
       tags: [GraphSync]
       operationId: f8a_jobs.api_v1.retrieve_graphsync_epv
       summary: Retrieve Pending Graphsync data for given ecosystem, package and version
       parameters:
        - $ref: "#/parameters/ecosystem_path"
        - $ref: "#/parameters/package_name"
        - $ref: "#/parameters/version_full"
        - $ref: "#/parameters/count"
       security:
        - auth_token: []
       responses:
         200:
           description: Summary of pending graphsync data for given ecosystem, package and version


  '/graphsync/sync_all':
    get:
       tags: [GraphSync]
       operationId: f8a_jobs.api_v1.invoke_graphsync_all
       summary: Invoke Graphsync for all ecosystems
       parameters:
        - $ref: "#/parameters/count"
       security:
        - auth_token: []
       responses:
         200:
           description: Invoke Graphsync for all ecosystems
  '/graphsync/sync_all/{ecosystem}':
    get:
       tags: [GraphSync]
       operationId: f8a_jobs.api_v1.invoke_graphsync_ecosystem
       summary: Invoke Graphsync for given ecosystem
       parameters:
        - $ref: "#/parameters/ecosystem_path"
        - $ref: "#/parameters/count"
       security:
        - auth_token: []
       responses:
         200:
           description: Invoke Graphsync for given ecosystem
  '/graphsync/sync_all/{ecosystem}/{package}':
    get:
       tags: [GraphSync]
       operationId: f8a_jobs.api_v1.invoke_graphsync_ecosystem_package
       summary: Invoke Graphsync for given ecosystem and package
       parameters:
        - $ref: "#/parameters/ecosystem_path"
        - $ref: "#/parameters/package_name"
        - $ref: "#/parameters/count"
       security:
        - auth_token: []
       responses:
         200:
           description: Invoke Graphsync for given ecosystem and package
  '/graphsync/sync_all/{ecosystem}/{package}/{version}':
    get:
       tags: [GraphSync]
       operationId: f8a_jobs.api_v1.invoke_graphsync_epv
       summary: Invoke Graphsync for given ecosystem, package and version
       parameters:
        - $ref: "#/parameters/ecosystem_path"
        - $ref: "#/parameters/package_name"
        - $ref: "#/parameters/version_full"
        - $ref: "#/parameters/count"
       security:
        - auth_token: []
       responses:
         200:
           description: Invoke Graphsync for given ecosystem, package and version
  '/jobs/invoke_graph_sync':
    post:
       tags: [Add new jobs]
       operationId: f8a_jobs.api_v1.post_invoke_graph_sync
       summary: Invoke Graphsync worker for given ecosystem, package and version
       security:
        - auth_token: []
       parameters:
        - name: kwargs
          in: body
          description: Arguments for the GraphSync job
          schema:
            $ref: "#/definitions/GraphSyncKwargs"
       responses:
         200:
           description: Invoke Graphsync Worker for given ecosystem, package and version

parameters:
  job_id_path:
    name: job_id
    in: path
    required: true
    description: Job identifier
    type: string
  package_name:
    name: package
    in: path
    required: true
    description: Package name
    type: string
  version_full:
    name: version
    in: path
    required: true
    description: Version
    type: string
  job_id:
    name: job_id
    in: query
    required: false
    description: Job identifier
    type: string
  periodically:
    name: periodically
    in: query
    type: string
    required: false
    description: Set periodical job execution
  when:
    name: when
    in: query
    type: string
    required: false
    description: Date time in UTC when the job run should be scheduled
  misfire_grace_time:
    name: misfire_grace_time
    in: query
    type: string
    required: false
    description: Time how much job’s execution is allowed to be late before throwing away
  state:
    name: state
    in: query
    required: true
    description: State
    type: string
    items:
      type: string
    enum:
      - running
      - paused
  job_type:
     name: job_type
     in: query
     required: false
     description: Job specific listing
     type: string
     items:
       type: string
     enum:
       - all
       - failed
       - user
     default: all
  popular:
    name: popular
    in: query
    required: false
    description: Sorted by popularity
    type: boolean
    default: false
  ecosystem:
     name: ecosystem
     in: query
     required: true
     description: Ecosystem
     type: string
     items:
       type: string
     enum:
       - maven
       - npm
       - pypi
       - nuget
       - go
  ecosystem_path:
     name: ecosystem
     in: path
     required: true
     description: Ecosystem
     type: string
     items:
       type: string
     enum:
       - maven
       - npm
       - pypi
       - nuget
       - go
  count:
    name: count
    in: query
    required: false
    description: Number (or dash-separated range) of items
    type: string
  min_stars:
    name: min_stars
    in: query
    required: false
    description: Minimum number of GitHub stars
    type: integer
  max_stars:
    name: max_stars
    in: query
    required: false
    description: Maximum number of GitHub stars
    type: integer
  skip_if_exists:
    name: skip_if_exists
    in: query
    required: false
    description: Do not process repositories for which results already exist
    type: boolean
    default: true
  start_from:
    name: start_from
    in: query
    required: false
    description: Skip first <number> most starred projects
    type: integer
  nversions:
    name: nversions
    in: query
    required: false
    description: Number of versions of each item (1 means latest version only)
    type: integer
  force:
    name: force
    in: query
    required: false
    description: Force analyses scheduling
    type: boolean
    default: false
  force_graph_sync:
    name: force_graph_sync
    in: query
    required: false
    description: Force graph synchronization of if already analysed
    type: boolean
    default: false
  start:
    name: start
    in: query
    required: false
    description: Analysis id to start syncing at
    type: integer
  end:
    name: end
    in: query
    required: false
    description: Analysis id to end syncing at
    type: integer
  from_date:
    name: from_date
    in: query
    required: false
    description: Limit by date and time
    type: string
  to_date:
    name: to_date
    in: query
    required: false
    description: Limit by date and time
    type: string
  recursive_limit:
    name: recursive_limit
    in: query
    required: false
    description: Number of recursive analyses
    type: integer
  bucket_name:
    name: bucket_name
    in: query
    required: true
    description: Name of the bucket to manipulate with
    type: string
  object_key:
    name: object_key
    in: query
    required: true
    description: Object key to manipulate with on S3
    type: string
  queues:
    name: queues
    in: query
    required: true
    description: A comma-separated list of queues to purge, without deployment prefix or star for all queues in deployment
    type: string
  offset:
    name: offset
    in: query
    required: true
    description: Offset to be used (positive integer)
    type: integer
  clean_unfinished:
    name: clean_unfinished
    in: query
    required: true
    description: DANGEROUS! Clean also entries of unfinished analyses, no analyses should be in progress
    type: boolean
    default: false
  user_persona:
    name: user_persona
    in: query
    required: true
    description: User type for which data is to be collected
    type: integer
    default: 1 
  past_days:
    name: past_days
    in: query
    required: true
    description: Append user data from past how many days.
    type: integer
    default: 7
  kronos_bucket:
    name: kronos_bucket
    in: query
    description: Name of the kronos bucket to manipulate.
    type: string
  active_only:
    name: active_only
    in: query
    required: true
    description: List active records only
    type: boolean
    default: false

definitions:
  FlowKwargs:
    type: object
    required:
      - flow_name
      - flow_arguments
    properties:
      flow_name: &flow_name_analysis
        type: string
        description: Selinon flow that should be run
        example: "bayesianFlow"
      flow_arguments: &flow_arguments
        type: array
        description: List of arguments that should be supplied per flow
        items:
          $ref: "#/definitions/Any"
        example:
          - ecosystem: "npm"
            name: "serve-static"
            version: "1.7.1"
            force: true
            recursive_limit: 0
            force_graph_sync: false
          - ecosystem: "maven"
            name: "net.iharder:base64"
            version: "2.3.9"
            force: true
            recursive_limit: 1
            force_graph_sync: false
  GraphSyncKwargs:
    type: object
    properties:
      ecosystem:
        type: string
        description: Ecosystem
        example: "npm"
      name:
        type: string
        description: Package name
        example: "serve-static"
      version:
        type: string
        description: Package Version
        example: "1.7.1"
  SelectiveKwargs:
    type: object
    required:
      - flow_name
      - task_names
      - flow_arguments
    properties:
      flow_name:
        <<: *flow_name_analysis
      task_names: &task_names
        type: array
        description: A list of tasks that should be run
        items:
          type: string
        example:
          - "github_details"
          - "ResultCollector"
      flow_arguments:
        <<: *flow_arguments
      run_subsequent:
        type: boolean
        description: Run nodes that are dependent on tasks listed in task_names
        example: false
  Filter:
    type: object
    required:
      - '$filter'
    additionalProperties: true
    properties:
      '$filter':
        type: object
        required:
          - table
        additionalProperties: true
        properties:
          table:
            type: string
            description: table to which the given query should be applied
            example: "versions"
          joins:
            type: array
            description: List of joins that should be applied (defaults to NATURAL JOIN)
            items:
              $ref: "#/definitions/Any"
            example:
              - table: "packages"
                'on':
                  versions.package_id: "packages.id"
              - table: "ecosystems"
                'on':
                  ecosystems.id: "packages.ecosystem_id"
          where:
            type: object
            description: WHERE clause that should be applied
            example:
              packages.name: "serve-static"
          select:
            type: array
            description: SELECT filtering
            items:
              type: string
            example:
              - "packages.name as name"
              - "ecosystems.name as ecosystem"
              - "versions.identifier as version"
  GitHubManifestsKwargs:
    type: object
    required:
      - repositories
    properties:
      repositories:
        type: array
        description: Array of keyword arguments for githubManifestMetadata flow
        items:
          $ref: "#/definitions/Any"
        example:
          - ecosystem: "maven"
            repo_name: "omalley/base64"
            force: true
            recursive_limit: 0
            force_graph_sync: false
          - ecosystem: "maven"
            repo_name: "jeremyh/jBCrypt"
            force: true
            recursive_limit: 0
            force_graph_sync: false
  GitHubAggregateManifestPkgsKwargs:
    type: object
    required:
      - repositories
    properties:
      repositories:
        type: array
        description: Array of repositories from which to aggregate packages
        items:
          $ref: "#/definitions/Any"
        example:
          - ecosystem: "maven"
            repo_name: "omalley/base64"
          - ecosystem: "maven"
            repo_name: "jeremyh/jBCrypt"

  Any:
    type: object
    additionalProperties: true
